server.port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: a
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect